const flashcards = [
    { term: "Metapher", definition: "Ein bildlicher Vergleich, bei dem die Gemeinsamkeit zwischen zwei Dingen nicht durch ein Vergleichswort (wie 'wie' oder 'als') ausgedrückt wird. Beispiel: 'Die Zeit ist ein Dieb'." },
    { term: "Vergleich", definition: "Die Ähnlichkeit zweier Dinge wird mit einem Vergleichswort (wie, als, gleich, so...) deutlich gemacht. Beispiel: 'Er ist stark wie ein Bär'." },
    { term: "Personifikation", definition: "Einem leblosen Gegenstand oder Tier werden menschliche Eigenschaften oder Verhaltensweisen zugeschrieben. Beispiel: 'Die Wellen tanzen über das Wasser'." },
    { term: "Alliteration", definition: "Die aufeinanderfolgende Verwendung von Wörtern, die mit demselben Konsonanten beginnen. Beispiel: 'Fischers Fritze fortfahren'." },
    { term: "Hyperbel", definition: "Eine bewusste Übertreibung, um eine Wirkung zu erzielen. Beispiel: 'Ich habe dir das schon tausendmal gesagt'." },
    { term: "Oxymoron", definition: "Die Verbindung von zwei widersprüchlichen Begriffen. Beispiel: 'Ein bittersüßer Sieg'." },
    { term: "Antithese", definition: "Die Gegenüberstellung von Gegensätzen. Beispiel: 'Liebe ist das Licht, Hass die Dunkelheit'." },
    { term: "Ironie", definition: "Die Verwendung von Worten, die das Gegenteil von dem ausdrücken, was gemeint ist, oft mit einer spöttischen Absicht. Beispiel: 'Toll gemacht!' (wenn jemand etwas kaputt macht)." },
    { term: "Aposiopese", definition: "Ein plötzliches Abbrechen des Redeflusses. Beispiel: 'Wenn ich nur wüsste, wer es war...'" },
    { term: "Epithet", definition: "Ein besonderes Eigenschaftswort, das ein Substantiv näher beschreibt. Beispiel: 'Das einsame Feld'." },
    { term: "Onomatopoetikon", definition: "Wörter, die das Geräusch nachahmen, das sie beschreiben. Beispiel: 'Kikerlzick', 'Brummen'." },
    { term: "Ellipse", definition: "Das weglassen von Worten, die aus dem Kontext ersichtlich sind. Beispiel: 'Gehen wir?' (statt 'Wollen wir gehen?')." },
    { term: "Anakoluth", definition: "Ein plötzlicher Bruch in der grammatikalischen Struktur eines Satzes. Beispiel: 'Ich wollte kommen, aber mein Hund, der bellte so laut...'" },
    { term: "Chiasmus", definition: "EineKreuzstellung von Worten oder Satzteilen. Beispiel: 'Ohrwurm oder Wortspiel'." },
    { term: "Synekdoche", definition: "Die Bezeichnung eines Ganzen durch einen Teil oder umgekehrt. Beispiel: 'Die Segel sind gesetzt' (für das Schiff)." },
    { term: "Metonymie", definition: "Die Bezeichnung eines Dinges durch ein anderes Ding, das in einer engen Wechselbeziehung steht. Beispiel: 'Das Schloss' (für den König)." },
    { term: "Pleonasmus", definition: "Eine unnötige Wortdopplung. Beispiel: 'Kalt wie Eis'." },
    { term: "Tautologie", definition: "Die Wiederholung desselben Inhalts mit verschiedenen Worten. Beispiel: 'Ich bin ganz und gar fertig'." },
    { term: "Rhetorische Frage", definition: "Eine Frage, auf die keine Antwort erwartet wird, die nur zur Unterstreichung einer Aussage dient. Beispiel: 'Wer kann das schon leiden?'" },
    { term: "Parenthese", definition: "Ein Einschub in einen Satz, der eine Zusatzinformation liefert. Beispiel: 'Er, ein tapferer Mann, kämpfte weiter'." },
    { term: "Anapher", definition: "Die Wiederholung desselben Wortes am Satzanfang. Beispiel: 'Ich will, ich will, ich will'." },
    { term: "Epizeuxis", definition: "Die Wiederholung desselben Wortes direkt hintereinander. Beispiel: 'Halt, halt, halt!'" },
    { term: "Litotes", definition: "Eine Untertreibung, die durch die Verneinung des Gegenteils ausgedrückt wird. Beispiel: 'Das ist nicht schlecht' (bedeutet: das ist gut)." },
    { term: "Apostrophe", definition: "Die direkte Anrede einer Person oder einer Personifizierung. Beispiel: 'O Tod, hülle mich bald!'" },
    { term: "Periphrase", definition: "Eine Umschreibung für ein Wort oder einen Begriff. Beispiel: 'Das Licht der Welt' (für Jesus)." },
    { term: "Euphemismus", definition: "Eine Abschwächung einer unangenehmen Aussage. Beispiel: 'Einschläfern' (für töten)." },
    { term: "Parapherse", definition: "Eine Umschreibung, die das Gegenteil eines Wortes ausdrückt. Beispiel: 'Ein Mensch ohne Worte' (für ein stummes Kind)." },
    { term: "Inversion", definition: "Die Umkehrung der normalen Satzstellung. Beispiel: 'Kommen Sie bitte her'." },
    { term: "Kollektion", definition: "Die Zusammenfassung mehrerer Begriffe unter einem Oberbegriff. Beispiel: 'Die Fahrzeuge' (für Autos, Busse, Fahrräder)." },
    { term: "Asyndeton", definition: "Das Weglassen von Konjunktionen in einer Aufzählung. Beispiel: 'Kommen, sehen, siegen'." },
    { term: "Polysyndeton", definition: "Die Häufung von Konjunktionen in einer Aufzählung. Beispiel: 'Und Wein und Brot und Liebe'." },
    { term: "Gradatio", definition: "Eine Steigerung von Begriffen oder Ausdrücken. Beispiel: 'Er kam, er sah, er siegte'." },
    { term: "Climax", definition: "Eine Steigerung von Bedeutung oder Intensität. Beispiel: 'Der Sieg war groß, der Ruhm war endlos'." },
    { term: "Antiklimax", definition: "Ein plötzlicher Abfall der Bedeutung oder Intensität. Beispiel: 'Er war ein Held, ein Krieger, ein Bettler'." },
    { term: "Tmesis", definition: "Das Einschieben eines Wortes in ein anderes Wort. Beispiel: 'Schad-enso-wenig'." },
    { term: "Zeugma", definition: "Die Verwendung eines Verbs für zwei unterschiedliche Bedeutungen. Beispiel: 'Er nahm seine Tasche und seinen Mut.'" },
    { term: "Homiletik", definition: "Die Verwendung von feststehenden, oft religiösen Floskeln. Beispiel: 'Gott sei Dank'." },
    { term: "Diminutiv", definition: "Die Verkleinerungsform eines Wortes. Beispiel: 'Häuschen'." },
    { term: "Superlativ", definition: "Die höchste Steigerungsstufe eines Adjektivs oder Adverbs. Beispiel: 'Am schönsten'." },
    { term: "Epizeuxis", definition: "Die sofortige Wiederholung eines Wortes zur Verstärkung. Beispiel: 'Halt, halt, halt!'" },
    { term: "Diakope", definition: "Die unmittelbare Wiederholung eines Wortes mit dazwischengeschobenen Wörtern. Beispiel: 'Halt, ein Moment, halt!'" },
    { term: "Epanalepsis", definition: "Die Wiederholung eines Wortes am Anfang und am Ende eines Satzes. Beispiel: 'Ganz gleich ist es, ganz gleich'." },
    { term: "Chiasmus", definition: "Kreuzstellung von Begriffen. Beispiel: 'Nicht nur Arbeit, sondern auch Ruhe'." },
    { term: "Metonymie", definition: "Bezeichnung durch eine damit verbundene Beziehung. Beispiel: 'Das Weiße Haus' (für die US-Regierung)." },
    { term: "Synekdoche", definition: "Bezeichnung des Ganzen durch einen Teil. Beispiel: 'Die Segel sind gesetzt'." },
    { term: "Hyperton", definition: "Eine bewusste Übertreibung der Bedeutung. Beispiel: 'Das schlägt ein wie eine Bombe'." },
    { term: "Anakoluth", definition: "Ein syntaktischer Bruch. Beispiel: 'Ich wollte gehen, aber dann das Wetter...'" },
    { term: "Parenthese", definition: "Ein Einschub in einen Satz. Beispiel: 'Er, der Mann, sah mich'." },
    { term: "Rhetorische Frage", definition: "Eine Frage ohne erwartete Antwort. Beispiel: 'Ist das nicht wunderbar?'" },
    { term: "Pleonasmus", definition: "Eine unnötige Dopplung. Beispiel: 'Ich sehe mit meinen Augen'." },
    { term: "Tautologie", definition: "Wiederholung desselben Inhalts. Beispiel: 'Das ist ein sicheres, sicheres Ziel'." }
];

const quizQuestions = [
    { question: "Die Sonne lacht über das Tal.", options: ["Metapher", "Personifikation", "Alliteration", "Hyperbel"], correct: 1 },
    { question: "Er ist stark wie ein Bär.", options: ["Vergleich", "Metapher", "Oxymoron", "Epizeuxis"], correct: 0 },
    { question: "Das Auto schrie vor Schmerz.", options: ["Alliteration", "Personifikation", "Hyperbel", "Chiasmus"], correct: 1 },
    { question: "Ich habe dir das schon ein Million Mal gesagt!", options: ["Hyperbel", "Litotes", "Simile", "Metapher"], correct: 0 },
    { question: "Ein bittersüßer Abschied.", options: ["Antithese", "Oxymoron", "Pleonasmus", "Ironie"], correct: 1 },
    { question: "Komm, schau, sieg!", options: ["Asyndeton", "Polysyndeton", "Gradatio", "Anapher"], correct: 0 },
    { question: "Er nahm seine Tasche und seine Zuversicht.", options: ["Zeugma", "Metapher", "Synekdoche", "Ellipse"], correct: 0 },
    { question: "Komm her, ich brauche dich, komm her!", options: ["Anapher", "Epizeuxis", "Alliteration", "Tautologie"], correct: 0 },
    { question: "Das weiße Haus gab eine Erklärung ab.", options: ["Metonymie", "Synekdoche", "Hyperbel", "Personifikation"], correct: 0 },
    { question: "Ich sehe mit meinen eigenen Augen.", options: ["Pleonasmus", "Tautologie", "Oxymoron", "Metapher"], correct: 0 },
    { question: "Das Licht der Welt.", options: ["Periphrase", "Metonymie", "Epithet", "Alliteration"], correct: 0 },
    { question: "Wer kann das schon leiden?", options: ["Rhetorische Frage", "Ironie", "Aposiopese", "Antithese"], correct: 0 },
    { question: "Das ist nicht gerade ein Problem.", options: ["Litotes", "Hyperbel", "Metapher", "Oxymoron"], correct: 0 },
    { question: "Die Wellen tanzen.", options: ["Personifikation", "Alliteration", "Hyperbel", "Vergleich"], correct: 0 },
    { question: "Ein einsames Feld unter blauem Himmel.", options: ["Epithet", "Metapher", "Simile", "Oxymoron"], correct: 0 },
    { question: "Das Boot segelte dahin, das Boot blieb stehen.", options: ["Anapher", "Epizeuxis", "Alliteration", "Asyndeton"], correct: 0 },
    { question: "Er war ein Held, ein Krieger, ein Bettler.", options: ["Antiklimax", "Climax", "Gradatio", "Chiasmus"], correct: 0 },
    { question: "Kalt wie Eis.", options: ["Pleonasmus", "Vergleich", "Metapher", "Oxymoron"], correct: 1 },
    { question: "Das Haus schallte von Lachen.", options: ["Personifikation", "Metapher", "Alliteration", "Hyperbel"], correct: 0 },
    { question: "Ich wollte gehen, aber die Zeit...", options: ["Aposiopese", "Ironie", "Anakoluth", "Ellipse"], correct: 0 },
    { question: "Ein schöner Tag, ein schöner Tag!", options: ["Epizeuxis", "Anapher", "Alliteration", "Tautologie"], correct: 0 },
    { question: "Lachen und Weinen.", options: ["Antithese", "Oxymoron", "Metapher", "Litotes"], correct: 0 },
    { question: "Er ist ein Löwe im Kampf.", options: ["Metapher", "Vergleich", "Personifikation", "Alliteration"], correct: 0 },
    { question: "Die Zeit rennt.", options: ["Personifikation", "Metapher", "Hyperbel", "Oxymoron"], correct: 0 },
    { question: "Ein stummer Schrei.", options: ["Oxymoron", "Antithese", "Pleonasmus", "Litotes"], correct: 0 },
    { question: "Der Wind heulte.", options: ["Personifikation", "Alliteration", "Metapher", "Hyperbel"], correct: 0 },
    { question: "Er war nicht gerade besonders klug.", options: ["Litotes", "Hyperbel", "Ironie", "Metapher"], correct: 0 },
    { question: "Das Herz ist ein Sturm.", options: ["Metapher", "Vergleich", "Personifikation", "Alliteration"], correct: 0 },
    { question: "Schau hin, schau hin!", options: ["Epizeuxis", "Anapher", "Alliteration", "Asyndeton"], correct: 0 },
    { question: "Er ist ein guter Mann.", options: ["Epithet", "Metapher", "Simile", "Oxymoron"], correct: 0 },
    { question: "Das Schiff ist in See.", options: ["Metonymie", "Synekdoche", "Metapher", "Hyperbel"], correct: 0 },
    { question: "Kommen, sehen, siegen.", options: ["Asyndeton", "Polysyndeton", "Gradatio", "Anapher"], correct: 0 },
    { question: "Er war ein König, ein Held, ein Mensch.", options: ["Gradatio", "Climax", "Antiklimax", "Chiasmus"], correct: 0 },
    { question: "Ich sehe dich, du siehst mich.", options: ["Chiasmus", "Antithese", "Oxymoron", "Pleonasmus"], correct: 0 },
    { question: "Ein leuchtendes Beispiel.", options: ["Metapher", "Oxymoron", "Epithet", "Alliteration"], correct: 0 },
    { question: "Das ist ein sicheres, sicheres Ziel.", options: ["Tautologie", "Pleonasmus", "Metapher", "Oxymoron"], correct: 0 },
    { question: "Er nahm seine Tasche und seinen Mut.", options: ["Zeugma", "Metapher", "Synekdoche", "Hyperbel"], correct: 0 },
    { question: "Der Tod ist ein Dieb.", options: ["Metapher", "Vergleich", "Personifikation", "Hyperbel"], correct: 0 },
    { question: "Ein kleiner Hund.", options: ["Diminutiv", "Superlativ", "Epithet", "Metapher"], correct: 0 },
    { question: "Das schönste Haus.", options: ["Superlativ", "Diminutiv", "Epithet", "Metapher"], correct: 0 },
    { question: "Ein Hauschen.", options: ["Diminutiv", "Superlativ", "Epithet", "Metapher"], correct: 0 },
    { question: "Oh, Schicksal!", options: ["Apostrophe", "Ironie", "Aposiopese", "Antithese"], correct: 0 },
    { question: "Er ist ein Mann von Welt.", options: ["Periphrase", "Metonymie", "Metapher", "Synekdoche"], correct: 0 },
    { question: "Das Leben ist ein Spiel.", options: ["Metapher", "Vergleich", "Personifikation", "Alliteration"], correct: 0 },
    { question: "Ein sanfter Wind.", options: ["Epithet", "Metapher", "Simile", "Oxymoron"], correct: 0 },
    { question: "Er hat mir die Welt gesagt.", options: ["Metonymie", "Synekdoche", "Metapher", "Hyperbel"], correct: 0 },
    { question: "Das Licht des Lebens.", options: ["Metapher", "Personifikation", "Epithet", "Alliteration"], correct: 0 },
    { question: "Er schlug sie mit voller Wucht.", options: ["Hyperbel", "Metapher", "Alliteration", "Oxymoron"], correct: 0 },
    { question: "Stille Nacht.", options: ["Epithet", "Metapher", "Simile", "Oxymoron"], correct: 0 },
    { question: "Wer weiß es schon?", options: ["Rhetorische Frage", "Ironie", "Aposiopese", "Antithese"], correct: 0 },
    { question: "Ein heißer Sommer.", options: ["Epithet", "Metapher", "Simile", "Oxymoron"], correct: 0 }
];
