const flashcards = [
    { term: "Akkumulation", definition: "Häufung von Wörtern oder Ausdrücken, die zu einem gemeinsamen Thema gehören, meist ohne Steigerung. Beispiel: 'Auf dem Markt gab es Obst, Gemüse, Käse, Brot und Fisch.'" },
    { term: "Allegorie", definition: "Die bildhafte Darstellung eines abstrakten Begriffs durch eine Person, ein Tier oder eine Szene. Beispiel: Justitia mit Waage und verbundenen Augen steht für die Gerechtigkeit." },
    { term: "Alliteration", definition: "Aufeinanderfolgende Wörter beginnen mit demselben Laut. Beispiel: 'Milch macht müde Männer munter.'" },
    { term: "Anapher", definition: "Wiederholung desselben Wortes oder derselben Wortgruppe am Anfang aufeinanderfolgender Sätze oder Verse. Beispiel: 'Alles ist vergangen, alles ist vorbei.'" },
    { term: "Antithese", definition: "Gegenüberstellung von gegensätzlichen Begriffen oder Gedanken. Beispiel: 'Der Anfang ist leicht, das Ende ist schwer.'" },
    { term: "Chiasmus", definition: "Kreuzstellung von Satzgliedern nach dem Schema A-B-B-A. Beispiel: 'Man lebt nicht, um zu essen, man isst, um zu leben.'" },
    { term: "Correctio", definition: "Verbesserung oder Korrektur einer eigenen Aussage, um sie zu verstärken oder zu präzisieren. Beispiel: 'Das war ein Fehler – nein, eine Katastrophe!'" },
    { term: "Ellipse", definition: "Auslassung von Satzteilen, die man sich aus dem Zusammenhang denken kann. Beispiel: 'Ende gut, alles gut.'" },
    { term: "Euphemismus", definition: "Beschönigende Umschreibung für etwas Unangenehmes. Beispiel: 'Er ist von uns gegangen.' (statt: gestorben)" },
    { term: "Hyperbel", definition: "Starke Übertreibung zur Verstärkung einer Aussage. Beispiel: 'Ich habe tausend Mal angerufen.'" },
    { term: "Inversion", definition: "Umstellung der üblichen Satzgliedfolge, um etwas zu betonen. Beispiel: 'Ein Mädchen sah ich dort stehen.'" },
    { term: "Ironie", definition: "Das Gegenteil des Gemeinten wird gesagt, oft spöttisch. Beispiel: 'Das hast du ja wieder prima hinbekommen!' (nach einem Missgeschick)" },
    { term: "Klimax", definition: "Steigerung über mehrere Glieder hinweg, z. B. in Bedeutung oder Intensität. Beispiel: 'Das Wasser reicht ihm bis zu den Knien, bis zum Bauch, bis zum Hals.'" },
    { term: "Metapher", definition: "Bildhafter Ausdruck ohne Vergleichswort: Ein Wort wird in übertragener Bedeutung verwendet. Beispiel: 'Sie hat ein Herz aus Stein.'" },
    { term: "Metonymie", definition: "Ein Begriff wird durch einen anderen ersetzt, der in sachlicher Beziehung zu ihm steht (z. B. Autor statt Werk). Beispiel: 'Ich lese gerade Goethe.'" },
    { term: "Neologismus", definition: "Neu gebildetes Wort oder neue Wortbedeutung. Beispiel: 'googeln' oder 'Wutbürger'." },
    { term: "Onomatopoesie", definition: "Lautmalerei: Wörter ahmen ein Geräusch nach. Beispiel: 'Es knistert, zischt und knallt.'" },
    { term: "Oxymoron", definition: "Verbindung zweier sich widersprechender Begriffe in einer Wortgruppe. Beispiel: 'beredtes Schweigen', 'bittersüß'." },
    { term: "Paradoxon", definition: "Scheinbar widersprüchliche Aussage, die bei genauerem Nachdenken einen tieferen Sinn enthält. Beispiel: 'Ich weiß, dass ich nichts weiß.'" },
    { term: "Parallelismus", definition: "Gleichartiger Satzbau in aufeinanderfolgenden Sätzen oder Satzteilen. Beispiel: 'Wer wagt, gewinnt. Wer wartet, verliert.'" },
    { term: "Personifikation", definition: "Dingen, Tieren oder Abstrakta werden menschliche Eigenschaften oder Handlungen zugeschrieben. Beispiel: 'Die Sonne lacht.'" },
    { term: "Rhetorische Frage", definition: "Scheinfrage, auf die keine Antwort erwartet wird, weil sie schon feststeht. Beispiel: 'Wer will das schon?'" },
    { term: "Symbol", definition: "Ein Bild oder Gegenstand, der über sich hinaus auf eine abstrakte Idee verweist. Beispiel: 'Die weiße Taube steht für den Frieden.'" },
    { term: "Vergleich", definition: "Zwei Dinge werden mit einem Vergleichswort (wie, als, gleich) in Beziehung gesetzt. Beispiel: 'Er ist stark wie ein Bär.'" }
];

// Hilfsfunktion: erster Eintrag der Antworten ist immer richtig, script.js mischt die Reihenfolge.
function q(question, correct, wrong) {
    return { question, options: [correct, ...wrong], correct: 0 };
}

const quizQuestions = [
    q("Auf dem Markt gab es Obst, Gemüse, Käse, Brot, Fisch und Gewürze.", "Akkumulation", ["Klimax", "Parallelismus", "Anapher"]),
    q("Lärm, Gestank, Hitze, Staub – die Stadt war unerträglich.", "Akkumulation", ["Antithese", "Ellipse", "Hyperbel"]),
    q("Justitia mit Waage und verbundenen Augen steht für die Gerechtigkeit.", "Allegorie", ["Neologismus", "Metonymie", "Ellipse"]),
    q("In der Fabel steht der listige Fuchs für den Betrüger und der Wolf für den Gewalttätigen.", "Allegorie", ["Oxymoron", "Euphemismus", "Inversion"]),
    q("Milch macht müde Männer munter.", "Alliteration", ["Anapher", "Onomatopoesie", "Parallelismus"]),
    q("Mit Mann und Maus gingen sie unter.", "Alliteration", ["Anapher", "Chiasmus", "Akkumulation"]),
    q("Ich will leben. Ich will lieben. Ich will frei sein.", "Anapher", ["Alliteration", "Chiasmus", "Euphemismus"]),
    q("Alles ist vergangen, alles ist vorbei, alles ist still.", "Anapher", ["Ironie", "Inversion", "Symbol"]),
    q("Der Anfang ist leicht, das Ende ist schwer.", "Antithese", ["Metonymie", "Hyperbel", "Neologismus"]),
    q("Die einen jubelten, die anderen weinten.", "Antithese", ["Ellipse", "Personifikation", "Symbol"]),
    q("Man lebt nicht, um zu essen, man isst, um zu leben.", "Chiasmus", ["Parallelismus", "Anapher", "Ellipse"]),
    q("Die Kunst ist lang, kurz ist das Leben.", "Chiasmus", ["Alliteration", "Hyperbel", "Euphemismus"]),
    q("Das war ein Fehler – nein, eine Katastrophe!", "Correctio", ["Anapher", "Ironie", "Ellipse"]),
    q("Er ist mein Freund, oder besser gesagt, mein Bruder.", "Correctio", ["Euphemismus", "Chiasmus", "Neologismus"]),
    q("Ende gut, alles gut.", "Ellipse", ["Inversion", "Parallelismus", "Correctio"]),
    q("Ich nach Hause, du zur Arbeit.", "Ellipse", ["Ironie", "Allegorie", "Neologismus"]),
    q("Er ist von uns gegangen.", "Euphemismus", ["Metonymie", "Ironie", "Hyperbel"]),
    q("Der Betrieb muss leider Personal freisetzen.", "Euphemismus", ["Hyperbel", "Ironie", "Oxymoron"]),
    q("Ich habe dir das schon tausend Mal gesagt!", "Hyperbel", ["Euphemismus", "Klimax", "Ironie"]),
    q("Hier ist seit Ewigkeiten nichts passiert.", "Hyperbel", ["Ellipse", "Euphemismus", "Symbol"]),
    q("Ein Mädchen sah ich dort stehen.", "Inversion", ["Ellipse", "Chiasmus", "Correctio"]),
    q("Gewaltig ist die Kraft der Natur.", "Inversion", ["Hyperbel", "Parallelismus", "Akkumulation"]),
    q("Na toll, jetzt regnet es auch noch – genau das Wetter, das ich mir gewünscht habe!", "Ironie", ["Hyperbel", "Euphemismus", "Paradoxon"]),
    q("Du hast das Glas fallen lassen? Das hast du ja wieder prima hinbekommen!", "Ironie", ["Antithese", "Correctio", "Metonymie"]),
    q("Das Wasser reicht ihm bis zu den Knien, bis zum Bauch, bis zum Hals.", "Klimax", ["Alliteration", "Inversion", "Symbol"]),
    q("Er war müde, erschöpft, am Ende seiner Kräfte.", "Klimax", ["Antithese", "Ellipse", "Chiasmus"]),
    q("Dieser Mann ist ein Fels in der Brandung.", "Metapher", ["Vergleich", "Hyperbel", "Ironie"]),
    q("Sie hat ein Herz aus Stein.", "Metapher", ["Vergleich", "Euphemismus", "Ellipse"]),
    q("Ich lese gerade Goethe.", "Metonymie", ["Metapher", "Symbol", "Neologismus"]),
    q("Er hat die ganze Flasche getrunken.", "Metonymie", ["Hyperbel", "Ellipse", "Alliteration"]),
    q("Ich muss das noch kurz googeln.", "Neologismus", ["Ellipse", "Euphemismus", "Onomatopoesie"]),
    q("Das Wort 'Wutbürger' wurde erst vor einigen Jahren neu gebildet.", "Neologismus", ["Metonymie", "Oxymoron", "Symbol"]),
    q("Es knistert, zischt und knallt.", "Onomatopoesie", ["Neologismus", "Anapher", "Hyperbel"]),
    q("Die Glocke machte bim-bam, bim-bam.", "Onomatopoesie", ["Parallelismus", "Ellipse", "Ironie"]),
    q("Ein beredtes Schweigen.", "Oxymoron", ["Euphemismus", "Hyperbel", "Ellipse"]),
    q("Ein bittersüßer Abschied.", "Oxymoron", ["Alliteration", "Inversion", "Symbol"]),
    q("Ich weiß, dass ich nichts weiß.", "Paradoxon", ["Ironie", "Ellipse", "Euphemismus"]),
    q("Weniger ist mehr.", "Paradoxon", ["Hyperbel", "Inversion", "Alliteration"]),
    q("Der eine liebt die Arbeit, der andere liebt die Ruhe.", "Parallelismus", ["Chiasmus", "Symbol", "Neologismus"]),
    q("Wer wagt, gewinnt. Wer wartet, verliert.", "Parallelismus", ["Chiasmus", "Inversion", "Euphemismus"]),
    q("Die Sonne lacht.", "Personifikation", ["Metonymie", "Vergleich", "Hyperbel"]),
    q("Der Wind flüstert durch die Bäume.", "Personifikation", ["Ironie", "Ellipse", "Symbol"]),
    q("Wer will das schon?", "Rhetorische Frage", ["Ironie", "Correctio", "Ellipse"]),
    q("Was kann es Schöneres geben als Freiheit?", "Rhetorische Frage", ["Hyperbel", "Inversion", "Euphemismus"]),
    q("Die weiße Taube steht für den Frieden.", "Symbol", ["Metonymie", "Ellipse", "Neologismus"]),
    q("Das Kreuz steht für das Christentum.", "Symbol", ["Hyperbel", "Ironie", "Inversion"]),
    q("Er ist stark wie ein Bär.", "Vergleich", ["Metapher", "Personifikation", "Symbol"]),
    q("Sie sang so schön wie eine Nachtigall.", "Vergleich", ["Metapher", "Hyperbel", "Ellipse"])
];